"""PDF rendering for AI Copilot research reports."""

import json
import re
from datetime import datetime, timezone
from io import BytesIO
from typing import Any, Mapping

from app.utils.logger import get_logger

logger = get_logger(__name__)


def _now_utc() -> datetime:
    return datetime.now(timezone.utc)


def _plain_text(value: Any) -> str:
    if value is None:
        return ""
    if isinstance(value, (dict, list, tuple)):
        return json.dumps(value, ensure_ascii=False)
    return str(value)

def _has_cjk_text(value: Any) -> bool:
    text = _plain_text(value)
    return bool(re.search(r"[\u2e80-\u9fff\uac00-\ud7af\u3040-\u30ff]", text))


def _register_report_pdf_font(prefer_cjk: bool = False) -> str:
    from pathlib import Path

    from reportlab.pdfbase import pdfmetrics
    from reportlab.pdfbase.ttfonts import TTFont

    candidates = [
        ("C:/Windows/Fonts/msyh.ttc", True),
        ("C:/Windows/Fonts/msyh.ttf", True),
        ("C:/Windows/Fonts/simsun.ttc", True),
        ("/usr/share/fonts/opentype/noto/NotoSansCJK-Regular.ttc", True),
        ("/usr/share/fonts/truetype/noto/NotoSansCJK-Regular.ttc", True),
        ("/usr/share/fonts/truetype/wqy/wqy-microhei.ttc", True),
        ("/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf", False),
    ]
    for path, is_cjk in candidates:
        if prefer_cjk and not is_cjk:
            continue
        try:
            if Path(path).exists():
                pdfmetrics.registerFont(TTFont("QuantDingerSans", path))
                return "QuantDingerSans"
        except Exception as e:
            logger.debug(f"Failed to register PDF font {path}: {e}")
    if prefer_cjk:
        try:
            from reportlab.pdfbase.cidfonts import UnicodeCIDFont

            pdfmetrics.registerFont(UnicodeCIDFont("STSong-Light"))
            return "STSong-Light"
        except Exception as e:
            logger.debug(f"Failed to register built-in CJK PDF font: {e}")
    return "Helvetica"


def _register_unicode_report_pdf_font() -> str:
    """Choose a TrueType Latin font before CJK collections for Vietnamese PDFs."""
    from pathlib import Path

    from reportlab.pdfbase import pdfmetrics
    from reportlab.pdfbase.ttfonts import TTFont

    candidates = [
        "C:/Windows/Fonts/arial.ttf",
        "C:/Windows/Fonts/segoeui.ttf",
        "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
        "/usr/share/fonts/truetype/liberation2/LiberationSans-Regular.ttf",
        "/usr/share/fonts/truetype/noto/NotoSans-Regular.ttf",
    ]
    for path in candidates:
        try:
            if Path(path).exists():
                pdfmetrics.registerFont(TTFont("DataVestUnicode", path))
                return "DataVestUnicode"
        except Exception as e:
            logger.debug(f"Failed to register Unicode PDF font {path}: {e}")
    return _register_report_pdf_font(prefer_cjk=False)


def _language_key(language: str = "") -> str:
    lang = (language or "").replace("_", "-").lower()
    if lang.startswith("zh-tw") or lang.startswith("zh-hk") or lang.startswith("zh-hant"):
        return "zh-TW"
    if lang.startswith("zh"):
        return "zh-CN"
    for key in ("ja", "ko", "de", "fr", "ru", "ar", "th", "vi"):
        if lang.startswith(key):
            return key
    return "en"


def _outlook_labels(language: str = "") -> dict[str, str]:
    labels = {
        "en": {"BUY": "Bullish", "SELL": "Bearish", "HOLD": "Neutral"},
        "zh-CN": {"BUY": "利多", "SELL": "利空", "HOLD": "中性"},
        "zh-TW": {"BUY": "利多", "SELL": "利空", "HOLD": "中性"},
        "ja": {"BUY": "強気", "SELL": "弱気", "HOLD": "中立"},
        "ko": {"BUY": "강세", "SELL": "약세", "HOLD": "중립"},
        "de": {"BUY": "Bullisch", "SELL": "Bärisch", "HOLD": "Neutral"},
        "fr": {"BUY": "Haussier", "SELL": "Baissier", "HOLD": "Neutre"},
        "ru": {"BUY": "Бычий", "SELL": "Медвежий", "HOLD": "Нейтральный"},
        "ar": {"BUY": "إيجابي", "SELL": "سلبي", "HOLD": "محايد"},
        "th": {"BUY": "เชิงบวก", "SELL": "เชิงลบ", "HOLD": "เป็นกลาง"},
        "vi": {"BUY": "Tích cực", "SELL": "Tiêu cực", "HOLD": "Trung lập"},
    }
    return labels.get(_language_key(language), labels["en"])


def _report_pdf_labels(language: str = "") -> dict[str, str]:
    labels = {
        "title": "QuantDinger AI Research Report",
        "subtitle": "AI-assisted market analysis for research use only",
        "target": "Target",
        "generated": "Generated",
        "decision": "Outlook",
        "confidence": "Confidence",
        "summary": "Executive Summary",
        "plan": "Trading Plan",
        "scores": "Model Scores",
        "trend": "Trend Outlook",
        "crypto": "Crypto Market Structure",
        "details": "Detailed Analysis",
        "reasons": "Key Reasons",
        "risks": "Risk Notes",
        "indicators": "Technical Indicators",
        "disclaimer": "This report is generated by AI for research only and is not investment advice.",
    }
    overrides = {
        "zh-CN": {
            "title": "QuantDinger AI 研究报告",
            "subtitle": "AI 辅助市场分析，仅供研究参考",
            "target": "分析标的",
            "generated": "生成时间",
            "decision": "观点",
            "confidence": "置信度",
            "summary": "核心摘要",
            "plan": "交易计划",
            "scores": "模型评分",
            "trend": "趋势展望",
            "crypto": "加密市场结构",
            "details": "详细分析",
            "reasons": "核心理由",
            "risks": "风险提示",
            "indicators": "技术指标",
            "disclaimer": "本报告由 AI 生成，仅供研究参考，不构成投资建议。",
        },
        "zh-TW": {
            "title": "QuantDinger AI 研究報告",
            "subtitle": "AI 輔助市場分析，僅供研究參考",
            "target": "分析標的",
            "generated": "生成時間",
            "decision": "觀點",
            "confidence": "信心度",
            "summary": "核心摘要",
            "plan": "交易計畫",
            "scores": "模型評分",
            "trend": "趨勢展望",
            "crypto": "加密市場結構",
            "details": "詳細分析",
            "reasons": "核心理由",
            "risks": "風險提示",
            "indicators": "技術指標",
            "disclaimer": "本報告由 AI 生成，僅供研究參考，不構成投資建議。",
        },
        "ja": {"decision": "見通し"},
        "ko": {"decision": "전망"},
        "de": {"decision": "Ausblick"},
        "fr": {"decision": "Perspective"},
        "ru": {"decision": "Прогноз"},
        "ar": {"decision": "التوقعات"},
        "th": {"decision": "มุมมอง"},
        "vi": {
            "title": "Báo cáo nghiên cứu AI DataVest",
            "subtitle": "Phân tích thị trường có AI hỗ trợ, chỉ dùng cho mục đích nghiên cứu",
            "target": "Tài sản phân tích",
            "generated": "Thời điểm tạo",
            "decision": "Nhận định",
            "confidence": "Độ tin cậy",
            "summary": "Tóm tắt chính",
            "plan": "Kế hoạch giao dịch",
            "scores": "Điểm mô hình",
            "trend": "Triển vọng xu hướng",
            "crypto": "Cấu trúc thị trường crypto",
            "details": "Phân tích chi tiết",
            "reasons": "Lý do chính",
            "risks": "Lưu ý rủi ro",
            "indicators": "Chỉ báo kỹ thuật",
            "disclaimer": "Báo cáo do AI tạo cho mục đích nghiên cứu, không phải tư vấn đầu tư.",
        },
    }
    labels.update(overrides.get(_language_key(language), {}))
    return labels


_TRADING_REPORT_TEAMS = {
    "analyst team reports",
    "research team decision",
    "trading team plan",
    "risk management team decision",
    "portfolio manager decision",
    "báo cáo nhóm phân tích",
    "quyết định của nhóm nghiên cứu",
    "kế hoạch của nhóm giao dịch",
    "quyết định của nhóm quản trị rủi ro",
    "quyết định của quản lý danh mục",
}

_TRADING_REPORT_ROLES = {
    "market analyst",
    "sentiment analyst",
    "news analyst",
    "fundamentals analyst",
    "bull researcher",
    "bear researcher",
    "research manager",
    "trader",
    "aggressive analyst",
    "conservative analyst",
    "neutral analyst",
    "portfolio manager",
    "chuyên gia phân tích thị trường",
    "chuyên gia phân tích tâm lý",
    "chuyên gia phân tích tin tức",
    "chuyên gia phân tích cơ bản",
    "nhà nghiên cứu xu hướng tăng",
    "nhà nghiên cứu xu hướng giảm",
    "quản lý nghiên cứu",
    "chuyên gia giao dịch",
    "chuyên gia chủ động",
    "chuyên gia thận trọng",
    "chuyên gia trung lập",
    "quản lý danh mục",
}

_TRADING_REPORT_CALLOUTS = {
    "action",
    "confidence",
    "decision",
    "final transaction proposal",
    "overall sentiment",
    "portfolio manager rating",
    "rating",
    "recommendation",
    "trader action",
}

_TRADING_REPORT_SECTION_LABELS = {
    "data validation",
    "data validation and discrepancy notes",
    "executive summary",
    "investment thesis",
    "risk control",
    "reasoning",
    "rationale",
    "strategic actions",
    "entry price",
    "stop loss",
    "stop-loss",
    "position sizing",
    "price target",
    "time horizon",
    "watchlist",
    "watchlist and scenarios",
    "danh sách theo dõi",
    "danh sách theo dõi và kịch bản",
    "phe bò",
    "phe gấu",
    "phe trung lập",
    "cân lại",
    "kết luận",
    "conclusion",
}


def _clean_trading_report_text(value: Any) -> str:
    text = re.sub(r"[*`#]", "", str(value or ""))
    # PDF text extraction can splice the repeated footer into the middle of
    # an agent paragraph. Remove only the known generated footer signature so
    # the saved TradingAgents prose remains intact.
    text = re.sub(
        r"(?:Không phải tư vấn đầu tư hoặc lệnh giao dịch\.|Not investment advice or an order instruction\.)?\s*DataVest\s*-\s*TradingAgents\s*-\s*\d+",
        " ",
        text,
        flags=re.IGNORECASE,
    )
    return re.sub(r"\s+", " ", text).strip()


def _trading_report_heading_key(value: str) -> str:
    cleaned = _clean_trading_report_text(value).rstrip(":").strip().casefold()
    return re.sub(r"^[ivxlc]+\.\s*", "", cleaned)


def _trading_report_tone(label: str, value: str) -> str:
    text = f"{label} {value}".casefold()
    if any(token in text for token in ("sell", "underweight", "bearish", "bán", "giảm", "hạ xuống")):
        return "negative"
    if any(token in text for token in ("buy", "overweight", "bullish", "mua", "tăng", "nâng lên")):
        return "positive"
    if any(token in text for token in ("hold", "neutral", "mixed", "giữ", "trung lập")):
        return "hold"
    return "info"


def _parse_trading_report_field(line: str) -> tuple[str, str] | None:
    match = re.match(r"^(?:\*\*)?(.{2,100}?)(?:\*\*)?\s*:\s*(.+)$", line.strip())
    if not match:
        return None
    label = _clean_trading_report_text(match.group(1)).strip()
    value = _clean_trading_report_text(match.group(2))
    return (label, value) if label and value else None


def _parse_trading_report_table_row(line: str) -> list[str]:
    return [_clean_trading_report_text(cell) for cell in line.strip().strip("|").split("|")]


def _is_trading_report_table_separator(row: list[str]) -> bool:
    return bool(row) and all(re.fullmatch(r":?-{3,}:?", cell.strip()) for cell in row)


def structure_trading_agents_report(content: str) -> list[dict[str, Any]]:
    """Normalize native TradingAgents markdown into a stable report hierarchy.

    The upstream agents can emit H1/H2 markdown, numbered headings, or plain
    text labels depending on the model/provider. The saved report writer adds
    the team and role wrappers, so normalize those wrappers to H1 → H2 → H3
    and keep all agent-authored analysis below its role at H4+.
    """
    lines = str(content or "").replace("\r\n", "\n").replace("\r", "\n").split("\n")
    blocks: list[dict[str, Any]] = []
    paragraph_lines: list[str] = []
    list_items: list[str] = []
    table_lines: list[str] = []
    fence = ""
    code_lines: list[str] = []
    inside_team = False
    inside_role = False

    def flush_paragraph() -> None:
        if paragraph_lines:
            text = _clean_trading_report_text(" ".join(paragraph_lines))
            if text:
                blocks.append({"type": "paragraph", "text": text})
            paragraph_lines.clear()

    def flush_list() -> None:
        if list_items:
            blocks.append({"type": "list", "items": [_clean_trading_report_text(item) for item in list_items]})
            list_items.clear()

    def flush_table() -> None:
        if len(table_lines) < 2:
            table_lines.clear()
            return
        rows = [_parse_trading_report_table_row(row) for row in table_lines]
        table_lines.clear()
        rows = [row for row in rows if row]
        if len(rows) < 2:
            return
        headers = rows[0]
        body = rows[2:] if _is_trading_report_table_separator(rows[1]) else rows[1:]
        if headers and body:
            blocks.append({
                "type": "table",
                "headers": headers,
                "rows": [row + [""] * (len(headers) - len(row)) for row in body],
            })

    def flush_all() -> None:
        flush_paragraph()
        flush_list()
        flush_table()

    def add_heading(text: str, level: int) -> None:
        clean = _clean_trading_report_text(text)
        if clean:
            blocks.append({"type": "heading", "level": level, "text": clean})

    def add_labeled_section(label: str, value: str) -> None:
        add_heading(label, 4)
        blocks.append({"type": "paragraph", "text": value})

    for raw_line in lines:
        line = raw_line.strip()
        fence_match = re.match(r"^(`{3,}|~{3,})", line)
        if fence:
            if fence_match and fence_match.group(1)[0] == fence[0] and len(fence_match.group(1)) >= len(fence):
                blocks.append({"type": "code", "text": "\n".join(code_lines)})
                fence = ""
                code_lines = []
            else:
                code_lines.append(raw_line)
            continue
        if fence_match:
            flush_all()
            fence = fence_match.group(1)
            continue
        if not line:
            flush_all()
            continue

        heading_match = re.match(r"^(#{1,6})\s+(.+)$", line)
        if heading_match:
            flush_all()
            source_level = len(heading_match.group(1))
            heading_text = heading_match.group(2).strip()
            heading_key = _trading_report_heading_key(heading_text)
            if heading_key in _TRADING_REPORT_TEAMS:
                add_heading(heading_text, 2)
                inside_team = True
                inside_role = False
            elif heading_key in _TRADING_REPORT_ROLES:
                add_heading(heading_text, 3)
                inside_team = True
                inside_role = True
            elif inside_role:
                add_heading(heading_text, min(6, 3 + max(1, source_level)))
            elif inside_team:
                add_heading(heading_text, min(6, 2 + max(1, source_level)))
            else:
                add_heading(heading_text, min(6, source_level))
            continue

        plain_key = _trading_report_heading_key(line)
        if plain_key in _TRADING_REPORT_TEAMS:
            flush_all()
            add_heading(line, 2)
            inside_team = True
            inside_role = False
            continue
        if plain_key in _TRADING_REPORT_ROLES:
            flush_all()
            add_heading(line, 3)
            inside_team = True
            inside_role = True
            continue

        normalized_line = _clean_trading_report_text(line)
        numbered = re.match(r"^(\d{1,2}[.)])\s+(.+)$", normalized_line)
        if inside_role and numbered:
            flush_all()
            add_heading(f"{numbered.group(1)} {numbered.group(2)}", 4)
            continue

        field = _parse_trading_report_field(line)
        if field:
            label, value = field
            label_key = label.casefold()
            if label_key in _TRADING_REPORT_CALLOUTS:
                flush_all()
                blocks.append({
                    "type": "callout",
                    "label": label,
                    "value": value,
                    "tone": _trading_report_tone(label, value),
                })
                continue
            if inside_role and label_key in _TRADING_REPORT_SECTION_LABELS:
                flush_all()
                add_labeled_section(label, value)
                continue

        thesis_marker = re.match(
            r"^(PHE\s+(?:BÒ|GẤU|TRUNG LẬP)|CÂN LẠI|DANH SÁCH THEO DÕI)(?:\s*\([^)]*\))?(?::|\s+)?(.*)$",
            normalized_line,
            flags=re.IGNORECASE,
        )
        if inside_role and thesis_marker:
            flush_all()
            label = thesis_marker.group(1)
            value = thesis_marker.group(2).strip()
            add_heading(label, 4)
            if value:
                blocks.append({"type": "paragraph", "text": value})
            continue

        list_match = re.match(r"^(?:[-*+]\s+)(.+)$", raw_line)
        if list_match:
            flush_table()
            flush_paragraph()
            list_items.append(list_match.group(1))
            continue
        if line.startswith("|") and line.endswith("|"):
            flush_paragraph()
            flush_list()
            table_lines.append(line)
            continue
        flush_table()
        flush_list()
        paragraph_lines.append(line)

    flush_all()
    if fence:
        blocks.append({"type": "code", "text": "\n".join(code_lines)})
    return blocks


def extract_portfolio_manager_decision(content: str) -> dict[str, Any]:
    """Return only the native section V decision, never a model-written summary."""
    lines = str(content or "").replace("\r\n", "\n").replace("\r", "\n").split("\n")
    section_title = ""
    section_lines: list[str] = []
    collecting = False

    for raw_line in lines:
        match = re.match(r"^##\s+(.+)$", raw_line.strip())
        if match:
            heading = match.group(1).strip()
            normalized = re.sub(r"^[IVXLC]+\.\s*", "", heading, flags=re.IGNORECASE).casefold()
            is_portfolio_decision = "portfolio manager" in normalized or "quản lý danh mục" in normalized
            if collecting:
                break
            if is_portfolio_decision:
                section_title = heading
                collecting = True
            continue
        if collecting:
            section_lines.append(raw_line)

    cards: list[tuple[str, str]] = []
    current_heading = ""
    paragraph_lines: list[str] = []

    def clean(value: str, limit: int = 1_200) -> str:
        text = _clean_trading_report_text(value)
        return text[:limit].rstrip()

    def add_card(title: str, value: str) -> None:
        card_title = clean(title, 100)
        card_value = clean(value)
        if card_title and card_value and len(cards) < 8:
            cards.append((card_title, card_value))

    def flush_paragraph() -> None:
        nonlocal paragraph_lines
        if paragraph_lines:
            add_card(current_heading or "Portfolio Manager Decision", " ".join(paragraph_lines))
            paragraph_lines = []

    for raw_line in section_lines:
        line = raw_line.strip()
        if not line:
            flush_paragraph()
            continue
        heading = re.match(r"^#{3,}\s+(.+)$", line)
        if heading:
            flush_paragraph()
            current_heading = heading.group(1).strip()
            continue
        field = re.match(r"^(?:[-*+]\s+)?(?:\*\*)?(.+?)(?:\*\*)?\s*:\s*(.+)$", line)
        if field:
            flush_paragraph()
            add_card(field.group(1), field.group(2))
            continue
        paragraph_lines.append(re.sub(r"^[-*+]\s+", "", line))
    flush_paragraph()

    return {"title": section_title, "cards": cards}


def extract_portfolio_manager_decision_sections(content: str) -> dict[str, Any]:
    """Structure direct facts from section V for the decision-summary template."""
    lines = str(content or "").replace("\r\n", "\n").replace("\r", "\n").split("\n")
    section_lines: list[str] = []
    section_title = ""
    collecting = False

    for raw_line in lines:
        line = raw_line.strip()
        heading = re.match(r"^#{1,6}\s+(.+)$", line)
        candidate = heading.group(1).strip() if heading else line
        normalized = re.sub(r"^[IVXLC]+\.\s*", "", candidate, flags=re.IGNORECASE).casefold()
        is_portfolio_decision = "portfolio manager" in normalized or "quản lý danh mục" in normalized
        if is_portfolio_decision and not collecting:
            section_title = candidate
            collecting = True
            continue
        # Keep role and nested analysis headings inside section V. Stop only
        # when the next document-level heading begins a new top-level section.
        if collecting and heading and len(heading.group(1)) <= 2:
            break
        if collecting:
            section_lines.append(raw_line)

    def clean(value: str, limit: int = 6_000) -> str:
        text = _clean_trading_report_text(value)
        return text[:limit].rstrip()

    def field_key(label: str) -> str | None:
        normalized = clean(label, 160).casefold()
        if "phe bò" in normalized:
            return "bull"
        if "phe gấu" in normalized:
            return "bear"
        if "phe trung lập" in normalized:
            return "neutral"
        if "cân lại" in normalized or "kết luận cân bằng" in normalized:
            return "balance"
        if "danh sách theo dõi" in normalized or "watchlist" in normalized:
            return "watchlist"
        if normalized.startswith("nâng") or "nâng rating" in normalized:
            return "upgrade"
        if normalized.startswith("hạ") or "hạ rating" in normalized:
            return "downgrade"
        if "time horizon" in normalized or "khung thời gian" in normalized:
            return "time_horizon"
        if normalized.startswith("portfolio manager rating"):
            return "rating"
        if normalized.startswith("rating") or normalized.startswith("khuyến nghị"):
            return "rating"
        if "executive summary" in normalized or "tóm tắt điều hành" in normalized:
            return "executive_summary"
        if "investment thesis" in normalized or "luận điểm đầu tư" in normalized:
            return "investment_thesis"
        return None

    fields: dict[str, str] = {}
    current_key: str | None = None
    for raw_line in section_lines:
        line = raw_line.strip()
        if not line:
            continue
        line = re.sub(r"^#{1,6}\s+", "", line)
        line = re.sub(r"^[-*+]\s+", "", line)
        thesis_marker = re.match(r"^(PHE (?:BÒ|GẤU|TRUNG LẬP))(?:\s*\([^)]*\))?(?::|\s+)?(.*)$", line, flags=re.IGNORECASE)
        if thesis_marker:
            key = field_key(thesis_marker.group(1))
            if key:
                fields[key] = clean(thesis_marker.group(2))
                current_key = key
                continue
        match = re.match(r"^(?:\*\*)?(.+?)(?:\*\*)?\s*:\s*(.+)$", line)
        if match:
            key = field_key(match.group(1))
            if key:
                fields[key] = clean(match.group(2))
                current_key = key
                continue
        inline_key = field_key(line)
        if inline_key and ":" not in line:
            current_key = inline_key
            continue
        if current_key:
            fields[current_key] = clean(f"{fields.get(current_key, '')} {line}")

    watchlist = fields.get("watchlist", "")
    scenario_markers = list(re.finditer(r"(?P<label>Nâng\s+lên.+?nếu|Hạ\s+xuống.+?nếu)\s*:\s*", watchlist, flags=re.IGNORECASE))
    if scenario_markers:
        fields["watchlist"] = clean(watchlist[:scenario_markers[0].start()])
        for index, marker in enumerate(scenario_markers):
            end = scenario_markers[index + 1].start() if index + 1 < len(scenario_markers) else len(watchlist)
            key = "upgrade" if marker.group("label").casefold().startswith("nâng") else "downgrade"
            fields[key] = clean(watchlist[marker.end():end])

    return {"title": section_title, "fields": fields}


def build_ai_report_pdf(report: dict, target: dict | None = None, language: str = "en-US") -> bytes:
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
    from reportlab.lib.units import mm
    from reportlab.platypus import (
        KeepTogether,
        Paragraph,
        SimpleDocTemplate,
        Spacer,
        Table,
        TableStyle,
    )

    target = target or {}
    zh = str(language or "").lower().startswith("zh")
    prefer_cjk = zh or _has_cjk_text(report) or _has_cjk_text(target)
    font_name = _register_report_pdf_font(prefer_cjk=prefer_cjk)
    width, height = A4
    buf = BytesIO()
    labels = _report_pdf_labels(language)

    doc = SimpleDocTemplate(
        buf,
        pagesize=A4,
        rightMargin=16 * mm,
        leftMargin=16 * mm,
        topMargin=18 * mm,
        bottomMargin=18 * mm,
        title=labels["title"],
    )
    content_width = width - doc.leftMargin - doc.rightMargin
    styles = getSampleStyleSheet()
    base_style = ParagraphStyle(
        "ReportBase",
        parent=styles["Normal"],
        fontName=font_name,
        fontSize=9.5,
        leading=15,
        textColor=colors.HexColor("#273449"),
        spaceAfter=4,
    )
    small_style = ParagraphStyle(
        "ReportSmall",
        parent=base_style,
        fontSize=8,
        leading=11,
        textColor=colors.HexColor("#667085"),
    )
    title_style = ParagraphStyle(
        "ReportTitle",
        parent=base_style,
        fontSize=22,
        leading=28,
        textColor=colors.white,
        spaceAfter=2,
    )
    section_style = ParagraphStyle(
        "ReportSection",
        parent=base_style,
        fontSize=13,
        leading=17,
        textColor=colors.HexColor("#0f2f55"),
        spaceBefore=10,
        spaceAfter=7,
    )
    table_head_style = ParagraphStyle(
        "ReportTableHead",
        parent=base_style,
        fontSize=8,
        leading=10,
        textColor=colors.HexColor("#667085"),
    )
    table_value_style = ParagraphStyle(
        "ReportTableValue",
        parent=base_style,
        fontSize=9,
        leading=12,
        textColor=colors.HexColor("#111827"),
    )

    def clean_text(value: Any) -> str:
        text = _plain_text(value).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
        return text.replace("\r\n", "\n").replace("\r", "\n").strip()

    def value_text(value: Any) -> str:
        if value in (None, ""):
            return "-"
        if isinstance(value, dict):
            parts = []
            preferred = ["trend", "direction", "score", "strength", "summary", "value", "signal"]
            keys = [key for key in preferred if key in value] + [key for key in value.keys() if key not in preferred]
            for key in keys[:4]:
                item = value.get(key)
                if item not in (None, "", [], {}):
                    parts.append(f"{str(key).replace('_', ' ').title()}: {value_text(item)}")
            return "; ".join(parts) or "-"
        if isinstance(value, (list, tuple)):
            return "; ".join(value_text(item) for item in value[:5] if item not in (None, "", [], {})) or "-"
        return clean_text(value)

    def p(text: Any, style: ParagraphStyle = base_style) -> Paragraph:
        return Paragraph(clean_text(text).replace("\n", "<br/>"), style)

    def section(title: str) -> list[Any]:
        return [Spacer(1, 5 * mm), Paragraph(clean_text(title), section_style)]

    def pair_table(items: list[tuple[str, Any]], columns: int = 2) -> Table:
        rows = []
        row = []
        for label, value in items:
            row.append([Paragraph(clean_text(label), table_head_style), Paragraph(value_text(value), table_value_style)])
            if len(row) == columns:
                rows.append(row)
                row = []
        if row:
            while len(row) < columns:
                row.append([Paragraph("", table_head_style), Paragraph("", table_value_style)])
            rows.append(row)

        col_width = content_width / columns
        table = Table(rows, colWidths=[col_width] * columns, hAlign="LEFT")
        table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#f7f9fc")),
            ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#d8e1ee")),
            ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#e6edf5")),
            ("LEFTPADDING", (0, 0), (-1, -1), 9),
            ("RIGHTPADDING", (0, 0), (-1, -1), 9),
            ("TOPPADDING", (0, 0), (-1, -1), 7),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 7),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ]))
        return table

    def simple_table(headers: list[str], rows: list[list[Any]]) -> Table:
        data = [[Paragraph(clean_text(header), table_head_style) for header in headers]]
        data.extend([[Paragraph(value_text(value), table_value_style) for value in row] for row in rows])
        table = Table(data, colWidths=[content_width / len(headers)] * len(headers), hAlign="LEFT", repeatRows=1)
        table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#eef4fb")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.HexColor("#42526e")),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#fafcff")]),
            ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#d8e1ee")),
            ("INNERGRID", (0, 0), (-1, -1), 0.35, colors.HexColor("#e6edf5")),
            ("LEFTPADDING", (0, 0), (-1, -1), 7),
            ("RIGHTPADDING", (0, 0), (-1, -1), 7),
            ("TOPPADDING", (0, 0), (-1, -1), 6),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ]))
        return table

    def bullet_block(items: Any) -> list[Any]:
        if not isinstance(items, list):
            return []
        return [p(f"- {value_text(item)}") for item in items if value_text(item) != "-"]

    def draw_page(canvas_obj: Any, document: Any) -> None:
        canvas_obj.saveState()
        canvas_obj.setFillColor(colors.HexColor("#8a94a6"))
        canvas_obj.setFont(font_name, 7.5)
        canvas_obj.drawString(doc.leftMargin, 9 * mm, labels["disclaimer"])
        canvas_obj.drawRightString(width - doc.rightMargin, 9 * mm, f"QuantDinger Research · {document.page}")
        canvas_obj.restoreState()

    symbol = report.get("symbol") or target.get("symbol") or ""
    market = report.get("market") or target.get("market") or ""
    decision = _plain_text(report.get("decision") or "HOLD").upper()
    decision_display = _outlook_labels(language).get(decision, decision)
    decision_color = colors.HexColor("#15803d" if decision == "BUY" else "#b91c1c" if decision == "SELL" else "#b7791f")
    story: list[Any] = []
    header = Table([
        [
            [Paragraph(labels["title"], title_style), Paragraph(labels["subtitle"], small_style)],
            [
                Paragraph(labels["decision"], small_style),
                Paragraph(decision_display, ParagraphStyle("Decision", parent=base_style, fontSize=20, leading=24, textColor=decision_color)),
            ],
        ]
    ], colWidths=[content_width * 0.72, content_width * 0.28])
    header.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#102033")),
        ("BOX", (0, 0), (-1, -1), 0, colors.HexColor("#102033")),
        ("LEFTPADDING", (0, 0), (-1, -1), 13),
        ("RIGHTPADDING", (0, 0), (-1, -1), 13),
        ("TOPPADDING", (0, 0), (-1, -1), 13),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 13),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
    ]))
    story.append(header)
    story.append(Spacer(1, 6 * mm))
    story.append(pair_table([
        (labels["target"], f"{market}:{symbol}" if market or symbol else "-"),
        (labels["generated"], _now_utc().strftime("%Y-%m-%d %H:%M UTC")),
        (labels["confidence"], report.get("confidence", "-")),
        (labels["decision"], decision_display),
    ], columns=2))

    if report.get("summary"):
        story.extend(section(labels["summary"]))
        story.append(p(report.get("summary")))

    market_data = report.get("market_data") if isinstance(report.get("market_data"), dict) else {}
    plan = report.get("trading_plan") if isinstance(report.get("trading_plan"), dict) else {}
    plan_items = [
        ("Current Price", market_data.get("current_price")),
        ("24h Change", market_data.get("change_24h")),
        ("Entry", plan.get("entry_price") or plan.get("entryPrice")),
        ("Stop Loss", plan.get("stop_loss") or plan.get("stopLoss")),
        ("Take Profit", plan.get("take_profit") or plan.get("takeProfit")),
        ("Risk/Reward", plan.get("risk_reward_ratio") or plan.get("riskRewardRatio")),
    ]
    if any(v not in (None, "") for _, v in plan_items):
        story.extend(section(labels["plan"]))
        story.append(pair_table([(k, "-" if v in (None, "") else v) for k, v in plan_items]))

    scores = report.get("scores") if isinstance(report.get("scores"), dict) else {}
    if scores:
        story.extend(section(labels["scores"]))
        story.append(pair_table([(str(k).replace("_", " ").title(), v) for k, v in scores.items()]))

    trend = report.get("trend_outlook") or report.get("trendOutlook")
    trend_summary = report.get("trend_outlook_summary") or report.get("trendOutlookSummary")
    if trend_summary or trend:
        story.extend(section(labels["trend"]))
        if trend_summary:
            story.append(p(trend_summary))
        if isinstance(trend, dict):
            story.append(simple_table(
                ["Horizon", "Outlook"] if not zh else ["周期", "预测"],
                [[str(k), v] for k, v in trend.items()],
            ))

    crypto_summary = report.get("crypto_factor_summary")
    crypto_factors = report.get("crypto_factors") if isinstance(report.get("crypto_factors"), dict) else {}
    if crypto_summary or crypto_factors:
        story.extend(section(labels["crypto"]))
        if crypto_summary:
            story.append(p(crypto_summary))
        if crypto_factors:
            story.append(pair_table([(str(k).replace("_", " "), v) for k, v in crypto_factors.items() if k != "signals"]))

    details = report.get("detailed_analysis") if isinstance(report.get("detailed_analysis"), dict) else {}
    if details:
        story.extend(section(labels["details"]))
        for key, value in details.items():
            story.append(KeepTogether([
                Paragraph(clean_text(str(key).replace("_", " ").title()), ParagraphStyle(
                    f"Detail{key}",
                    parent=base_style,
                    fontSize=10.5,
                    leading=14,
                    textColor=colors.HexColor("#0f2f55"),
                    spaceBefore=3,
                )),
                p(value),
            ]))

    if report.get("reasons"):
        story.extend(section(labels["reasons"]))
        story.extend(bullet_block(report.get("reasons")))
    if report.get("risks"):
        story.extend(section(labels["risks"]))
        story.extend(bullet_block(report.get("risks")))

    indicators = report.get("indicators") if isinstance(report.get("indicators"), dict) else {}
    if indicators:
        story.extend(section(labels["indicators"]))
        story.append(pair_table([(str(k).replace("_", " "), v) for k, v in indicators.items()]))

    doc.build(story, onFirstPage=draw_page, onLaterPages=draw_page)
    return buf.getvalue()


def build_trading_agents_report_pdf(
    *,
    content: str,
    market: str,
    symbol: str,
    analysis_date: str,
    language: str,
    run_id: str,
) -> bytes:
    """Render the immutable native TradingAgents Markdown artifact as a PDF."""
    from reportlab.lib import colors
    from reportlab.lib.enums import TA_RIGHT
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
    from reportlab.lib.units import mm
    from reportlab.platypus import PageBreak, Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

    is_vietnamese = _language_key(language) == "vi"
    labels = {
        "title": "Báo cáo chuyên sâu TradingAgents" if is_vietnamese else "TradingAgents Deep Research Report",
        "subtitle": "Báo cáo gốc đã xác thực, chỉ phục vụ mục đích nghiên cứu" if is_vietnamese else "Verified native report for research use only",
        "asset": "Tài sản" if is_vietnamese else "Asset",
        "date": "Ngày phân tích" if is_vietnamese else "Analysis date",
        "run": "Mã lần chạy" if is_vietnamese else "Run ID",
        "summary": "TÓM TẮT BÁO CÁO QUYẾT ĐỊNH DANH MỤC ĐẦU TƯ" if is_vietnamese else "PORTFOLIO DECISION REPORT SUMMARY",
        "summary_note": "Tách trực tiếp từ Mục V của báo cáo TradingAgents; không dùng tóm tắt LLM." if is_vietnamese else "Directly structured from section V of the native TradingAgents report; no LLM summary.",
        "action": "1. TÓM TẮT HÀNH ĐỘNG" if is_vietnamese else "1. ACTION SUMMARY",
        "thesis": "2. LUẬN ĐIỂM ĐẦU TƯ" if is_vietnamese else "2. INVESTMENT THESIS",
        "scenarios": "3. DANH SÁCH THEO DÕI & KỊCH BẢN" if is_vietnamese else "3. WATCHLIST & SCENARIOS",
        "rating": "RATING" if is_vietnamese else "RATING",
        "time_horizon": "Khung thời gian" if is_vietnamese else "Time horizon",
        "core_strategy": "Chiến lược cốt lõi" if is_vietnamese else "Core strategy",
        "capital_management": "Quản trị vốn" if is_vietnamese else "Capital management",
        "stop_loss": "Kỷ luật cắt lỗ" if is_vietnamese else "Stop-loss discipline",
        "add_position": "Điều kiện mua thêm/DCA" if is_vietnamese else "Add position/DCA conditions",
        "bull": "Phe Bò - tích cực" if is_vietnamese else "Bull case",
        "bear": "Phe Gấu - thận trọng" if is_vietnamese else "Bear case",
        "neutral": "Phe Trung lập - cân bằng" if is_vietnamese else "Neutral case",
        "balance": "Kết luận của Portfolio Manager" if is_vietnamese else "Portfolio Manager conclusion",
        "upgrade": "Nâng rating" if is_vietnamese else "Upgrade rating",
        "downgrade": "Hạ rating" if is_vietnamese else "Downgrade rating",
        "unavailable": "Báo cáo gốc chưa có Mục V. Quyết định quản lý danh mục." if is_vietnamese else "The native report does not contain a Portfolio Manager Decision section.",
        "disclaimer": "Không phải tư vấn đầu tư hoặc lệnh giao dịch." if is_vietnamese else "Not investment advice or an order instruction.",
    }
    font_name = _register_unicode_report_pdf_font() if is_vietnamese else _register_report_pdf_font(prefer_cjk=_has_cjk_text(content))
    buffer = BytesIO()
    page_width, _ = A4
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=16 * mm,
        leftMargin=16 * mm,
        topMargin=18 * mm,
        bottomMargin=18 * mm,
        title=labels["title"],
    )
    styles = getSampleStyleSheet()
    base = ParagraphStyle(
        "TradingAgentsPdfBase",
        parent=styles["Normal"],
        fontName=font_name,
        fontSize=10,
        leading=15.5,
        textColor=colors.HexColor("#273449"),
        spaceAfter=7,
    )
    title = ParagraphStyle(
        "TradingAgentsPdfTitle",
        parent=base,
        fontSize=21,
        leading=27,
        textColor=colors.white,
    )
    subtitle = ParagraphStyle(
        "TradingAgentsPdfSubtitle",
        parent=base,
        fontSize=8.5,
        leading=12,
        textColor=colors.HexColor("#cbd5e1"),
    )
    heading = ParagraphStyle(
        "TradingAgentsPdfHeading",
        parent=base,
        fontSize=13.5,
        leading=18,
        textColor=colors.HexColor("#12355b"),
        spaceBefore=10,
        spaceAfter=5,
    )
    subheading = ParagraphStyle(
        "TradingAgentsPdfSubheading",
        parent=heading,
        fontSize=11,
        leading=15,
        spaceBefore=8,
        spaceAfter=4,
    )
    team_heading = ParagraphStyle(
        "TradingAgentsPdfTeamHeading",
        parent=base,
        fontSize=13.5,
        leading=18,
        textColor=colors.white,
        spaceAfter=0,
    )
    role_heading = ParagraphStyle(
        "TradingAgentsPdfRoleHeading",
        parent=base,
        fontSize=12.5,
        leading=17,
        textColor=colors.HexColor("#123b61"),
        spaceAfter=0,
    )
    detail_heading = ParagraphStyle(
        "TradingAgentsPdfDetailHeading",
        parent=base,
        fontSize=10.5,
        leading=14,
        textColor=colors.HexColor("#14532d"),
        spaceAfter=0,
    )
    small = ParagraphStyle(
        "TradingAgentsPdfSmall",
        parent=base,
        fontSize=8,
        leading=11,
        textColor=colors.HexColor("#64748b"),
    )
    bullet = ParagraphStyle(
        "TradingAgentsPdfBullet",
        parent=base,
        leftIndent=7 * mm,
        firstLineIndent=-4 * mm,
        bulletIndent=0,
        spaceAfter=3,
    )
    table_header = ParagraphStyle(
        "TradingAgentsPdfTableHeader",
        parent=small,
        fontSize=8.2,
        leading=10.5,
        textColor=colors.HexColor("#17395f"),
    )
    table_cell = ParagraphStyle(
        "TradingAgentsPdfTableCell",
        parent=base,
        fontSize=8.7,
        leading=11.5,
        spaceAfter=0,
    )
    callout_label = ParagraphStyle(
        "TradingAgentsPdfCalloutLabel",
        parent=small,
        fontSize=8,
        leading=10,
        textColor=colors.HexColor("#475569"),
        spaceAfter=0,
    )
    callout_value = ParagraphStyle(
        "TradingAgentsPdfCalloutValue",
        parent=base,
        fontSize=12.5,
        leading=16,
        textColor=colors.HexColor("#172033"),
        spaceAfter=0,
    )

    def escaped(value: object) -> str:
        return _plain_text(value).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").strip()

    def formatted(value: object) -> str:
        text = escaped(value)
        text = re.sub(r"`([^`]+)`", r'<font color="#0f5f7a">\1</font>', text)
        text = re.sub(r"\*\*(.+?)\*\*", r"<b>\1</b>", text)
        text = re.sub(r"(?<!\*)\*([^*]+)\*(?!\*)", r"<i>\1</i>", text)
        return text

    def paragraph(value: object, style: ParagraphStyle = base) -> Paragraph:
        return Paragraph(formatted(value).replace("\n", "<br/>"), style)

    portfolio_decision = extract_portfolio_manager_decision(content)
    portfolio_sections = extract_portfolio_manager_decision_sections(content)
    story: list[object] = []

    def compact_summary(value: str, limit: int = 260) -> str:
        cleaned = re.sub(r"\s+", " ", re.sub(r"[*`#]", "", value)).strip()
        if len(cleaned) <= limit:
            return cleaned
        return f"{cleaned[:limit].rsplit(' ', 1)[0].rstrip()}..."

    def append_report_summary() -> None:
        summary_title = ParagraphStyle(
            "TradingAgentsPdfSummaryTitle", parent=heading, fontSize=14, leading=18, textColor=colors.white, spaceAfter=0
        )
        summary_note = ParagraphStyle(
            "TradingAgentsPdfSummaryNote", parent=small, fontSize=8.3, leading=11.5, textColor=colors.HexColor("#dbeafe"), spaceAfter=0
        )
        summary_label = ParagraphStyle(
            "TradingAgentsPdfSummaryLabel", parent=small, fontSize=8, leading=10, textColor=colors.HexColor("#52677f"), spaceAfter=0
        )
        summary_value = ParagraphStyle(
            "TradingAgentsPdfSummaryValue", parent=base, fontSize=9.4, leading=13.2, textColor=colors.HexColor("#1e293b"), spaceAfter=0
        )
        fields = portfolio_sections["fields"]

        def sentences(value: str, limit: int = 4) -> list[str]:
            parts = re.split(r"(?<=[.!?])\s+(?=[A-ZÀ-Ỵ])", clean_text(value))
            return [compact_summary(item, 320) for item in parts if item.strip()][:limit]

        def clean_text(value: str) -> str:
            return re.sub(r"\s+", " ", re.sub(r"[*`#]", "", str(value or ""))).strip()

        def first_matching(items: list[str], expressions: tuple[str, ...]) -> str:
            for item in items:
                lowered = item.casefold()
                if any(expression in lowered for expression in expressions):
                    return item
            return ""

        def action_rows() -> list[tuple[str, str]]:
            executive_summary = fields.get("executive_summary", "")
            fragments = sentences(executive_summary, limit=8)
            if not fragments:
                return [(compact_summary(title, 100), compact_summary(value, 820)) for title, value in portfolio_decision["cards"][:4]]
            rows = [(labels["core_strategy"], fragments[0])]
            categories = [
                (labels["capital_management"], ("sizing", "đòn bẩy", "tiền mặt", "cắt tỉa", "tỷ trọng", "quản trị vốn")),
                (labels["stop_loss"], ("stop", "thủng", "phòng thủ", "cắt lỗ")),
                (labels["add_position"], ("thêm vị thế", "dca", "gia tăng", "mua thêm", "đóng cửa trên")),
            ]
            seen = {fragments[0]}
            for label, expressions in categories:
                match = first_matching(fragments, expressions)
                if match and match not in seen:
                    rows.append((label, match))
                    seen.add(match)
            return rows

        def heading_row(text: str, accent: str) -> Table:
            table = Table([[Paragraph(text, subheading)]], colWidths=[doc.width], hAlign="LEFT")
            table.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#edf5fa")),
                ("LINEBEFORE", (0, 0), (0, -1), 3, colors.HexColor(accent)),
                ("LEFTPADDING", (0, 0), (-1, -1), 10),
                ("RIGHTPADDING", (0, 0), (-1, -1), 10),
                ("TOPPADDING", (0, 0), (-1, -1), 5),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
            ]))
            return table

        def summary_card(label: str, value: str, background: str, accent: str) -> Table:
            card = Table(
                [[Paragraph(label.upper(), summary_label), Paragraph(formatted(compact_summary(value, 900)).replace("\n", "<br/>"), summary_value)]],
                colWidths=[doc.width * 0.26, doc.width * 0.74],
                hAlign="LEFT",
            )
            card.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor(background)),
                ("LINEBEFORE", (0, 0), (0, -1), 3, colors.HexColor(accent)),
                ("BOX", (0, 0), (-1, -1), 0.35, colors.HexColor("#dce6f0")),
                ("LEFTPADDING", (0, 0), (-1, -1), 9),
                ("RIGHTPADDING", (0, 0), (-1, -1), 9),
                ("TOPPADDING", (0, 0), (-1, -1), 6),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ]))
            return card

        summary_header = Table(
            [[Paragraph(labels["summary"], summary_title)], [Paragraph(labels["summary_note"], summary_note)]],
            colWidths=[doc.width],
            hAlign="LEFT",
        )
        summary_header.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#123b61")),
            ("LINEBEFORE", (0, 0), (0, -1), 4, colors.HexColor("#22c55e")),
            ("LEFTPADDING", (0, 0), (-1, -1), 12),
            ("RIGHTPADDING", (0, 0), (-1, -1), 12),
            ("TOPPADDING", (0, 0), (-1, 0), 8),
            ("BOTTOMPADDING", (0, 0), (-1, 0), 2),
            ("TOPPADDING", (0, 1), (-1, 1), 1),
            ("BOTTOMPADDING", (0, 1), (-1, 1), 8),
        ]))
        story.extend([Spacer(1, 5 * mm), summary_header, Spacer(1, 2.2 * mm)])

        rating = clean_text(fields.get("rating", "Hold")).upper()
        rating_color = "#d97706" if "HOLD" in rating or "GIỮ" in rating else "#16a34a" if any(token in rating for token in ("BUY", "OVERWEIGHT", "MUA")) else "#dc2626"
        decision_snapshot = Table([[
            [Paragraph(labels["rating"], summary_label), Paragraph(rating, ParagraphStyle("TradingAgentsPdfRating", parent=summary_value, fontSize=18, leading=22, textColor=colors.HexColor(rating_color)))],
            [Paragraph(labels["asset"], summary_label), Paragraph(escaped(symbol), ParagraphStyle("TradingAgentsPdfAsset", parent=summary_value, fontSize=12, leading=16, textColor=colors.HexColor("#123b61")))],
            [Paragraph(labels["time_horizon"], summary_label), Paragraph(escaped(fields.get("time_horizon", "-")), ParagraphStyle("TradingAgentsPdfHorizon", parent=summary_value, fontSize=11, leading=15, textColor=colors.HexColor("#123b61")))],
        ]], colWidths=[doc.width / 3] * 3, hAlign="LEFT")
        decision_snapshot.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#f8fbff")),
            ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#d8e7f4")),
            ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#d8e7f4")),
            ("LEFTPADDING", (0, 0), (-1, -1), 9),
            ("RIGHTPADDING", (0, 0), (-1, -1), 9),
            ("TOPPADDING", (0, 0), (-1, -1), 8),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ]))
        story.extend([decision_snapshot, Spacer(1, 2.4 * mm)])

        actions = action_rows()
        if actions:
            story.extend([heading_row(labels["action"], "#16a34a"), Spacer(1, 1.6 * mm)])
            for index, (label, value) in enumerate(actions):
                story.extend([summary_card(label, value, "#f7fcf8", "#16a34a"), Spacer(1, 1.3 * mm)])

        thesis_values = [
            (labels["bull"], fields.get("bull", ""), "#ecfdf3", "#16a34a"),
            (labels["bear"], fields.get("bear", ""), "#fff7ed", "#dc2626"),
            (labels["neutral"], fields.get("neutral", ""), "#fffbeb", "#d97706"),
            (labels["balance"], fields.get("balance", fields.get("investment_thesis", "")), "#eff6ff", "#2563eb"),
        ]
        if any(value for _, value, _, _ in thesis_values):
            story.extend([heading_row(labels["thesis"], "#2563eb"), Spacer(1, 1.6 * mm)])
            for label, value, background, accent in thesis_values:
                if value:
                    story.extend([summary_card(label, value, background, accent), Spacer(1, 1.3 * mm)])

        scenarios = [
            (labels["upgrade"], fields.get("upgrade", ""), "#ecfdf3", "#16a34a"),
            (labels["downgrade"], fields.get("downgrade", ""), "#fff1f2", "#dc2626"),
        ]
        if fields.get("watchlist") or any(value for _, value, _, _ in scenarios):
            story.extend([heading_row(labels["scenarios"], "#7c3aed"), Spacer(1, 1.6 * mm)])
            if fields.get("watchlist"):
                story.extend([summary_card("Watchlist", fields["watchlist"], "#f5f3ff", "#7c3aed"), Spacer(1, 1.3 * mm)])
            for label, value, background, accent in scenarios:
                if value:
                    story.extend([summary_card(label, value, background, accent), Spacer(1, 1.3 * mm)])

        if not fields and not portfolio_decision["cards"]:
            unavailable = Table([[Paragraph(labels["unavailable"], summary_value)]], colWidths=[doc.width], hAlign="LEFT")
            unavailable.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#fff7ed")),
                ("LINEBEFORE", (0, 0), (0, -1), 3, colors.HexColor("#d97706")),
                ("BOX", (0, 0), (-1, -1), 0.35, colors.HexColor("#f1d6b8")),
                ("LEFTPADDING", (0, 0), (-1, -1), 10),
                ("RIGHTPADDING", (0, 0), (-1, -1), 10),
                ("TOPPADDING", (0, 0), (-1, -1), 8),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
            ]))
            story.append(unavailable)
        story.append(PageBreak())

    header = Table(
        [[
            [Paragraph(labels["title"], title), Paragraph(labels["subtitle"], subtitle)],
            Paragraph(f"{escaped(market)}<br/><b>{escaped(symbol)}</b>", ParagraphStyle(
                "TradingAgentsPdfTarget", parent=base, fontSize=12, leading=17, textColor=colors.white, alignment=TA_RIGHT
            )),
        ]],
        colWidths=[doc.width * 0.72, doc.width * 0.28],
    )
    header.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#102033")),
        ("LEFTPADDING", (0, 0), (-1, -1), 14),
        ("RIGHTPADDING", (0, 0), (-1, -1), 14),
        ("TOPPADDING", (0, 0), (-1, -1), 14),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 14),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
    ]))
    story.extend([header, Spacer(1, 6 * mm)])

    metadata = Table([[
        [Paragraph(labels["asset"], small), paragraph(f"{market}: {symbol}")],
        [Paragraph(labels["date"], small), paragraph(analysis_date)],
        [Paragraph(labels["run"], small), paragraph(run_id)],
    ]], colWidths=[doc.width / 3] * 3, hAlign="LEFT")
    metadata.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#f5f8fc")),
        ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#d8e1ee")),
        ("INNERGRID", (0, 0), (-1, -1), 5, colors.white),
        ("LEFTPADDING", (0, 0), (-1, -1), 9),
        ("RIGHTPADDING", (0, 0), (-1, -1), 9),
        ("TOPPADDING", (0, 0), (-1, -1), 7),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 7),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
    ]))
    story.append(metadata)
    append_report_summary()

    def append_hierarchy_heading(title_text: str, level: int) -> None:
        if level <= 2:
            style = team_heading
            background = "#123b61"
            accent = "#22c55e"
            before = 4
        elif level == 3:
            style = role_heading
            background = "#eaf3fb"
            accent = "#2563eb"
            before = 3
        else:
            style = detail_heading
            background = "#f1f8f3"
            accent = "#16a34a" if level == 4 else "#94a3b8"
            before = 2
        heading_row = Table([[paragraph(title_text, style)]], colWidths=[doc.width], hAlign="LEFT")
        heading_row.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor(background)),
            ("LINEBEFORE", (0, 0), (0, -1), 4 if level <= 2 else 3, colors.HexColor(accent)),
            ("LEFTPADDING", (0, 0), (-1, -1), 10 if level <= 3 else 8),
            ("RIGHTPADDING", (0, 0), (-1, -1), 10),
            ("TOPPADDING", (0, 0), (-1, -1), 7 if level <= 3 else 5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 7 if level <= 3 else 5),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ]))
        story.extend([Spacer(1, before * mm), heading_row, Spacer(1, 1.5 * mm)])

    def append_callout(block: dict[str, Any]) -> None:
        tone = str(block.get("tone") or "info")
        palette = {
            "positive": ("#ecfdf3", "#16a34a"),
            "negative": ("#fff1f2", "#dc2626"),
            "hold": ("#fffbeb", "#d97706"),
            "info": ("#eff6ff", "#2563eb"),
        }
        background, accent = palette.get(tone, palette["info"])
        table = Table(
            [[
                Paragraph(escaped(block.get("label", "Decision")).upper(), callout_label),
                Paragraph(formatted(block.get("value", "")), callout_value),
            ]],
            colWidths=[doc.width * 0.34, doc.width * 0.66],
            hAlign="LEFT",
        )
        table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor(background)),
            ("LINEBEFORE", (0, 0), (0, -1), 4, colors.HexColor(accent)),
            ("BOX", (0, 0), (-1, -1), 0.45, colors.HexColor("#d8e1ee")),
            ("LEFTPADDING", (0, 0), (-1, -1), 10),
            ("RIGHTPADDING", (0, 0), (-1, -1), 10),
            ("TOPPADDING", (0, 0), (-1, -1), 7),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 7),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ]))
        story.extend([Spacer(1, 1.4 * mm), table, Spacer(1, 1.4 * mm)])

    def is_table_divider(cells: list[str]) -> bool:
        return bool(cells) and all(re.fullmatch(r":?-{3,}:?", cell.strip()) for cell in cells)

    def append_table(rows: list[list[str]]) -> None:
        if not rows:
            return
        has_header = len(rows) > 1 and is_table_divider(rows[1])
        body_rows = [rows[0]] + rows[2:] if has_header else rows
        column_count = max(len(row) for row in body_rows)
        padded_rows = [row + [""] * (column_count - len(row)) for row in body_rows]
        rendered_rows = []
        for row_index, row in enumerate(padded_rows):
            style = table_header if has_header and row_index == 0 else table_cell
            rendered_rows.append([paragraph(cell, style) for cell in row])
        report_table = Table(
            rendered_rows,
            colWidths=[doc.width / column_count] * column_count,
            repeatRows=1 if has_header else 0,
            hAlign="LEFT",
        )
        report_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#e8f1f8") if has_header else colors.white),
            ("BACKGROUND", (0, 1 if has_header else 0), (-1, -1), colors.HexColor("#fbfdff")),
            ("GRID", (0, 0), (-1, -1), 0.45, colors.HexColor("#d6e2ed")),
            ("LEFTPADDING", (0, 0), (-1, -1), 7),
            ("RIGHTPADDING", (0, 0), (-1, -1), 7),
            ("TOPPADDING", (0, 0), (-1, -1), 6),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ]))
        story.extend([Spacer(1, 2 * mm), report_table, Spacer(1, 2 * mm)])

    for block_index, block in enumerate(structure_trading_agents_report(content)):
        block_type = block.get("type")
        if block_type == "heading":
            level = int(block.get("level") or 4)
            heading_text = str(block.get("text") or "")
            if level == 1 and heading_text.casefold().startswith("trading analysis report:"):
                continue
            append_hierarchy_heading(heading_text, level)
        elif block_type == "callout":
            append_callout(block)
        elif block_type == "list":
            for item in block.get("items", []):
                story.append(paragraph(f"• {item}", bullet))
        elif block_type == "table":
            rows = [block.get("headers", [])]
            rows.append(["---"] * len(rows[0]))
            rows.extend(block.get("rows", []))
            append_table(rows)
        elif block_type == "code":
            code_style = ParagraphStyle(f"TradingAgentsPdfCode{block_index}", parent=small, backColor=colors.HexColor("#f8fafc"), borderColor=colors.HexColor("#d8e1ee"), borderWidth=0.5, borderPadding=6, fontName=font_name, leading=11)
            story.append(paragraph(block.get("text", ""), code_style))
        elif block_type == "paragraph":
            story.append(paragraph(block.get("text", "")))

    def draw_page(canvas_obj: object, document: object) -> None:
        canvas_obj.saveState()
        canvas_obj.setFillColor(colors.HexColor("#64748b"))
        canvas_obj.setFont(font_name, 7.5)
        canvas_obj.drawString(doc.leftMargin, 9 * mm, labels["disclaimer"])
        canvas_obj.drawRightString(page_width - doc.rightMargin, 9 * mm, f"DataVest - TradingAgents - {document.page}")
        canvas_obj.restoreState()

    doc.build(story, onFirstPage=draw_page, onLaterPages=draw_page)
    return buffer.getvalue()

