"""PDF rendering for AI Copilot research reports."""

import json
import re
from datetime import datetime, timezone
from io import BytesIO
from typing import Any, Mapping

from app.utils.logger import get_logger

logger = get_logger(__name__)


def _now_utc() -> datetime:
    return datetime.now(timezone.utc)


def _plain_text(value: Any) -> str:
    if value is None:
        return ""
    if isinstance(value, (dict, list, tuple)):
        return json.dumps(value, ensure_ascii=False)
    return str(value)

def _has_cjk_text(value: Any) -> bool:
    text = _plain_text(value)
    return bool(re.search(r"[\u2e80-\u9fff\uac00-\ud7af\u3040-\u30ff]", text))


def _register_report_pdf_font(prefer_cjk: bool = False) -> str:
    from pathlib import Path

    from reportlab.pdfbase import pdfmetrics
    from reportlab.pdfbase.ttfonts import TTFont

    candidates = [
        ("C:/Windows/Fonts/msyh.ttc", True),
        ("C:/Windows/Fonts/msyh.ttf", True),
        ("C:/Windows/Fonts/simsun.ttc", True),
        ("/usr/share/fonts/opentype/noto/NotoSansCJK-Regular.ttc", True),
        ("/usr/share/fonts/truetype/noto/NotoSansCJK-Regular.ttc", True),
        ("/usr/share/fonts/truetype/wqy/wqy-microhei.ttc", True),
        ("/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf", False),
    ]
    for path, is_cjk in candidates:
        if prefer_cjk and not is_cjk:
            continue
        try:
            if Path(path).exists():
                pdfmetrics.registerFont(TTFont("QuantDingerSans", path))
                return "QuantDingerSans"
        except Exception as e:
            logger.debug(f"Failed to register PDF font {path}: {e}")
    if prefer_cjk:
        try:
            from reportlab.pdfbase.cidfonts import UnicodeCIDFont

            pdfmetrics.registerFont(UnicodeCIDFont("STSong-Light"))
            return "STSong-Light"
        except Exception as e:
            logger.debug(f"Failed to register built-in CJK PDF font: {e}")
    return "Helvetica"


def _register_unicode_report_pdf_font() -> str:
    """Choose a TrueType Latin font before CJK collections for Vietnamese PDFs."""
    from pathlib import Path

    from reportlab.pdfbase import pdfmetrics
    from reportlab.pdfbase.ttfonts import TTFont

    candidates = [
        "C:/Windows/Fonts/arial.ttf",
        "C:/Windows/Fonts/segoeui.ttf",
        "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
        "/usr/share/fonts/truetype/liberation2/LiberationSans-Regular.ttf",
        "/usr/share/fonts/truetype/noto/NotoSans-Regular.ttf",
    ]
    for path in candidates:
        try:
            if Path(path).exists():
                pdfmetrics.registerFont(TTFont("DataVestUnicode", path))
                return "DataVestUnicode"
        except Exception as e:
            logger.debug(f"Failed to register Unicode PDF font {path}: {e}")
    return _register_report_pdf_font(prefer_cjk=False)


def _language_key(language: str = "") -> str:
    lang = (language or "").replace("_", "-").lower()
    if lang.startswith("zh-tw") or lang.startswith("zh-hk") or lang.startswith("zh-hant"):
        return "zh-TW"
    if lang.startswith("zh"):
        return "zh-CN"
    for key in ("ja", "ko", "de", "fr", "ru", "ar", "th", "vi"):
        if lang.startswith(key):
            return key
    return "en"


def _outlook_labels(language: str = "") -> dict[str, str]:
    labels = {
        "en": {"BUY": "Bullish", "SELL": "Bearish", "HOLD": "Neutral"},
        "zh-CN": {"BUY": "利多", "SELL": "利空", "HOLD": "中性"},
        "zh-TW": {"BUY": "利多", "SELL": "利空", "HOLD": "中性"},
        "ja": {"BUY": "強気", "SELL": "弱気", "HOLD": "中立"},
        "ko": {"BUY": "강세", "SELL": "약세", "HOLD": "중립"},
        "de": {"BUY": "Bullisch", "SELL": "Bärisch", "HOLD": "Neutral"},
        "fr": {"BUY": "Haussier", "SELL": "Baissier", "HOLD": "Neutre"},
        "ru": {"BUY": "Бычий", "SELL": "Медвежий", "HOLD": "Нейтральный"},
        "ar": {"BUY": "إيجابي", "SELL": "سلبي", "HOLD": "محايد"},
        "th": {"BUY": "เชิงบวก", "SELL": "เชิงลบ", "HOLD": "เป็นกลาง"},
        "vi": {"BUY": "Tích cực", "SELL": "Tiêu cực", "HOLD": "Trung lập"},
    }
    return labels.get(_language_key(language), labels["en"])


def _report_pdf_labels(language: str = "") -> dict[str, str]:
    labels = {
        "title": "QuantDinger AI Research Report",
        "subtitle": "AI-assisted market analysis for research use only",
        "target": "Target",
        "generated": "Generated",
        "decision": "Outlook",
        "confidence": "Confidence",
        "summary": "Executive Summary",
        "plan": "Trading Plan",
        "scores": "Model Scores",
        "trend": "Trend Outlook",
        "crypto": "Crypto Market Structure",
        "details": "Detailed Analysis",
        "reasons": "Key Reasons",
        "risks": "Risk Notes",
        "indicators": "Technical Indicators",
        "disclaimer": "This report is generated by AI for research only and is not investment advice.",
    }
    overrides = {
        "zh-CN": {
            "title": "QuantDinger AI 研究报告",
            "subtitle": "AI 辅助市场分析，仅供研究参考",
            "target": "分析标的",
            "generated": "生成时间",
            "decision": "观点",
            "confidence": "置信度",
            "summary": "核心摘要",
            "plan": "交易计划",
            "scores": "模型评分",
            "trend": "趋势展望",
            "crypto": "加密市场结构",
            "details": "详细分析",
            "reasons": "核心理由",
            "risks": "风险提示",
            "indicators": "技术指标",
            "disclaimer": "本报告由 AI 生成，仅供研究参考，不构成投资建议。",
        },
        "zh-TW": {
            "title": "QuantDinger AI 研究報告",
            "subtitle": "AI 輔助市場分析，僅供研究參考",
            "target": "分析標的",
            "generated": "生成時間",
            "decision": "觀點",
            "confidence": "信心度",
            "summary": "核心摘要",
            "plan": "交易計畫",
            "scores": "模型評分",
            "trend": "趨勢展望",
            "crypto": "加密市場結構",
            "details": "詳細分析",
            "reasons": "核心理由",
            "risks": "風險提示",
            "indicators": "技術指標",
            "disclaimer": "本報告由 AI 生成，僅供研究參考，不構成投資建議。",
        },
        "ja": {"decision": "見通し"},
        "ko": {"decision": "전망"},
        "de": {"decision": "Ausblick"},
        "fr": {"decision": "Perspective"},
        "ru": {"decision": "Прогноз"},
        "ar": {"decision": "التوقعات"},
        "th": {"decision": "มุมมอง"},
        "vi": {
            "title": "Báo cáo nghiên cứu AI DataVest",
            "subtitle": "Phân tích thị trường có AI hỗ trợ, chỉ dùng cho mục đích nghiên cứu",
            "target": "Tài sản phân tích",
            "generated": "Thời điểm tạo",
            "decision": "Nhận định",
            "confidence": "Độ tin cậy",
            "summary": "Tóm tắt chính",
            "plan": "Kế hoạch giao dịch",
            "scores": "Điểm mô hình",
            "trend": "Triển vọng xu hướng",
            "crypto": "Cấu trúc thị trường crypto",
            "details": "Phân tích chi tiết",
            "reasons": "Lý do chính",
            "risks": "Lưu ý rủi ro",
            "indicators": "Chỉ báo kỹ thuật",
            "disclaimer": "Báo cáo do AI tạo cho mục đích nghiên cứu, không phải tư vấn đầu tư.",
        },
    }
    labels.update(overrides.get(_language_key(language), {}))
    return labels


def build_ai_report_pdf(report: dict, target: dict | None = None, language: str = "en-US") -> bytes:
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
    from reportlab.lib.units import mm
    from reportlab.platypus import (
        KeepTogether,
        Paragraph,
        SimpleDocTemplate,
        Spacer,
        Table,
        TableStyle,
    )

    target = target or {}
    zh = str(language or "").lower().startswith("zh")
    prefer_cjk = zh or _has_cjk_text(report) or _has_cjk_text(target)
    font_name = _register_report_pdf_font(prefer_cjk=prefer_cjk)
    width, height = A4
    buf = BytesIO()
    labels = _report_pdf_labels(language)

    doc = SimpleDocTemplate(
        buf,
        pagesize=A4,
        rightMargin=16 * mm,
        leftMargin=16 * mm,
        topMargin=18 * mm,
        bottomMargin=18 * mm,
        title=labels["title"],
    )
    content_width = width - doc.leftMargin - doc.rightMargin
    styles = getSampleStyleSheet()
    base_style = ParagraphStyle(
        "ReportBase",
        parent=styles["Normal"],
        fontName=font_name,
        fontSize=9.5,
        leading=15,
        textColor=colors.HexColor("#273449"),
        spaceAfter=4,
    )
    small_style = ParagraphStyle(
        "ReportSmall",
        parent=base_style,
        fontSize=8,
        leading=11,
        textColor=colors.HexColor("#667085"),
    )
    title_style = ParagraphStyle(
        "ReportTitle",
        parent=base_style,
        fontSize=22,
        leading=28,
        textColor=colors.white,
        spaceAfter=2,
    )
    section_style = ParagraphStyle(
        "ReportSection",
        parent=base_style,
        fontSize=13,
        leading=17,
        textColor=colors.HexColor("#0f2f55"),
        spaceBefore=10,
        spaceAfter=7,
    )
    table_head_style = ParagraphStyle(
        "ReportTableHead",
        parent=base_style,
        fontSize=8,
        leading=10,
        textColor=colors.HexColor("#667085"),
    )
    table_value_style = ParagraphStyle(
        "ReportTableValue",
        parent=base_style,
        fontSize=9,
        leading=12,
        textColor=colors.HexColor("#111827"),
    )

    def clean_text(value: Any) -> str:
        text = _plain_text(value).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
        return text.replace("\r\n", "\n").replace("\r", "\n").strip()

    def value_text(value: Any) -> str:
        if value in (None, ""):
            return "-"
        if isinstance(value, dict):
            parts = []
            preferred = ["trend", "direction", "score", "strength", "summary", "value", "signal"]
            keys = [key for key in preferred if key in value] + [key for key in value.keys() if key not in preferred]
            for key in keys[:4]:
                item = value.get(key)
                if item not in (None, "", [], {}):
                    parts.append(f"{str(key).replace('_', ' ').title()}: {value_text(item)}")
            return "; ".join(parts) or "-"
        if isinstance(value, (list, tuple)):
            return "; ".join(value_text(item) for item in value[:5] if item not in (None, "", [], {})) or "-"
        return clean_text(value)

    def p(text: Any, style: ParagraphStyle = base_style) -> Paragraph:
        return Paragraph(clean_text(text).replace("\n", "<br/>"), style)

    def section(title: str) -> list[Any]:
        return [Spacer(1, 5 * mm), Paragraph(clean_text(title), section_style)]

    def pair_table(items: list[tuple[str, Any]], columns: int = 2) -> Table:
        rows = []
        row = []
        for label, value in items:
            row.append([Paragraph(clean_text(label), table_head_style), Paragraph(value_text(value), table_value_style)])
            if len(row) == columns:
                rows.append(row)
                row = []
        if row:
            while len(row) < columns:
                row.append([Paragraph("", table_head_style), Paragraph("", table_value_style)])
            rows.append(row)

        col_width = content_width / columns
        table = Table(rows, colWidths=[col_width] * columns, hAlign="LEFT")
        table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#f7f9fc")),
            ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#d8e1ee")),
            ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#e6edf5")),
            ("LEFTPADDING", (0, 0), (-1, -1), 9),
            ("RIGHTPADDING", (0, 0), (-1, -1), 9),
            ("TOPPADDING", (0, 0), (-1, -1), 7),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 7),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ]))
        return table

    def simple_table(headers: list[str], rows: list[list[Any]]) -> Table:
        data = [[Paragraph(clean_text(header), table_head_style) for header in headers]]
        data.extend([[Paragraph(value_text(value), table_value_style) for value in row] for row in rows])
        table = Table(data, colWidths=[content_width / len(headers)] * len(headers), hAlign="LEFT", repeatRows=1)
        table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#eef4fb")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.HexColor("#42526e")),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#fafcff")]),
            ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#d8e1ee")),
            ("INNERGRID", (0, 0), (-1, -1), 0.35, colors.HexColor("#e6edf5")),
            ("LEFTPADDING", (0, 0), (-1, -1), 7),
            ("RIGHTPADDING", (0, 0), (-1, -1), 7),
            ("TOPPADDING", (0, 0), (-1, -1), 6),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ]))
        return table

    def bullet_block(items: Any) -> list[Any]:
        if not isinstance(items, list):
            return []
        return [p(f"- {value_text(item)}") for item in items if value_text(item) != "-"]

    def draw_page(canvas_obj: Any, document: Any) -> None:
        canvas_obj.saveState()
        canvas_obj.setFillColor(colors.HexColor("#8a94a6"))
        canvas_obj.setFont(font_name, 7.5)
        canvas_obj.drawString(doc.leftMargin, 9 * mm, labels["disclaimer"])
        canvas_obj.drawRightString(width - doc.rightMargin, 9 * mm, f"QuantDinger Research · {document.page}")
        canvas_obj.restoreState()

    symbol = report.get("symbol") or target.get("symbol") or ""
    market = report.get("market") or target.get("market") or ""
    decision = _plain_text(report.get("decision") or "HOLD").upper()
    decision_display = _outlook_labels(language).get(decision, decision)
    decision_color = colors.HexColor("#15803d" if decision == "BUY" else "#b91c1c" if decision == "SELL" else "#b7791f")
    story: list[Any] = []
    header = Table([
        [
            [Paragraph(labels["title"], title_style), Paragraph(labels["subtitle"], small_style)],
            [
                Paragraph(labels["decision"], small_style),
                Paragraph(decision_display, ParagraphStyle("Decision", parent=base_style, fontSize=20, leading=24, textColor=decision_color)),
            ],
        ]
    ], colWidths=[content_width * 0.72, content_width * 0.28])
    header.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#102033")),
        ("BOX", (0, 0), (-1, -1), 0, colors.HexColor("#102033")),
        ("LEFTPADDING", (0, 0), (-1, -1), 13),
        ("RIGHTPADDING", (0, 0), (-1, -1), 13),
        ("TOPPADDING", (0, 0), (-1, -1), 13),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 13),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
    ]))
    story.append(header)
    story.append(Spacer(1, 6 * mm))
    story.append(pair_table([
        (labels["target"], f"{market}:{symbol}" if market or symbol else "-"),
        (labels["generated"], _now_utc().strftime("%Y-%m-%d %H:%M UTC")),
        (labels["confidence"], report.get("confidence", "-")),
        (labels["decision"], decision_display),
    ], columns=2))

    if report.get("summary"):
        story.extend(section(labels["summary"]))
        story.append(p(report.get("summary")))

    market_data = report.get("market_data") if isinstance(report.get("market_data"), dict) else {}
    plan = report.get("trading_plan") if isinstance(report.get("trading_plan"), dict) else {}
    plan_items = [
        ("Current Price", market_data.get("current_price")),
        ("24h Change", market_data.get("change_24h")),
        ("Entry", plan.get("entry_price") or plan.get("entryPrice")),
        ("Stop Loss", plan.get("stop_loss") or plan.get("stopLoss")),
        ("Take Profit", plan.get("take_profit") or plan.get("takeProfit")),
        ("Risk/Reward", plan.get("risk_reward_ratio") or plan.get("riskRewardRatio")),
    ]
    if any(v not in (None, "") for _, v in plan_items):
        story.extend(section(labels["plan"]))
        story.append(pair_table([(k, "-" if v in (None, "") else v) for k, v in plan_items]))

    scores = report.get("scores") if isinstance(report.get("scores"), dict) else {}
    if scores:
        story.extend(section(labels["scores"]))
        story.append(pair_table([(str(k).replace("_", " ").title(), v) for k, v in scores.items()]))

    trend = report.get("trend_outlook") or report.get("trendOutlook")
    trend_summary = report.get("trend_outlook_summary") or report.get("trendOutlookSummary")
    if trend_summary or trend:
        story.extend(section(labels["trend"]))
        if trend_summary:
            story.append(p(trend_summary))
        if isinstance(trend, dict):
            story.append(simple_table(
                ["Horizon", "Outlook"] if not zh else ["周期", "预测"],
                [[str(k), v] for k, v in trend.items()],
            ))

    crypto_summary = report.get("crypto_factor_summary")
    crypto_factors = report.get("crypto_factors") if isinstance(report.get("crypto_factors"), dict) else {}
    if crypto_summary or crypto_factors:
        story.extend(section(labels["crypto"]))
        if crypto_summary:
            story.append(p(crypto_summary))
        if crypto_factors:
            story.append(pair_table([(str(k).replace("_", " "), v) for k, v in crypto_factors.items() if k != "signals"]))

    details = report.get("detailed_analysis") if isinstance(report.get("detailed_analysis"), dict) else {}
    if details:
        story.extend(section(labels["details"]))
        for key, value in details.items():
            story.append(KeepTogether([
                Paragraph(clean_text(str(key).replace("_", " ").title()), ParagraphStyle(
                    f"Detail{key}",
                    parent=base_style,
                    fontSize=10.5,
                    leading=14,
                    textColor=colors.HexColor("#0f2f55"),
                    spaceBefore=3,
                )),
                p(value),
            ]))

    if report.get("reasons"):
        story.extend(section(labels["reasons"]))
        story.extend(bullet_block(report.get("reasons")))
    if report.get("risks"):
        story.extend(section(labels["risks"]))
        story.extend(bullet_block(report.get("risks")))

    indicators = report.get("indicators") if isinstance(report.get("indicators"), dict) else {}
    if indicators:
        story.extend(section(labels["indicators"]))
        story.append(pair_table([(str(k).replace("_", " "), v) for k, v in indicators.items()]))

    doc.build(story, onFirstPage=draw_page, onLaterPages=draw_page)
    return buf.getvalue()


def build_trading_agents_report_pdf(
    *,
    content: str,
    market: str,
    symbol: str,
    analysis_date: str,
    language: str,
    run_id: str,
    executive_summary: Mapping[str, Any] | None = None,
) -> bytes:
    """Render the immutable native TradingAgents Markdown artifact as a PDF."""
    from reportlab.lib import colors
    from reportlab.lib.enums import TA_RIGHT
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
    from reportlab.lib.units import mm
    from reportlab.platypus import HRFlowable, PageBreak, Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

    is_vietnamese = _language_key(language) == "vi"
    labels = {
        "title": "Báo cáo chuyên sâu TradingAgents" if is_vietnamese else "TradingAgents Deep Research Report",
        "subtitle": "Báo cáo gốc đã xác thực, chỉ phục vụ mục đích nghiên cứu" if is_vietnamese else "Verified native report for research use only",
        "asset": "Tài sản" if is_vietnamese else "Asset",
        "date": "Ngày phân tích" if is_vietnamese else "Analysis date",
        "run": "Mã lần chạy" if is_vietnamese else "Run ID",
        "summary": "Tóm tắt toàn bộ báo cáo" if is_vietnamese else "Whole-report summary",
        "summary_note": "Tóm lược tự động từ các kết luận đã có trong báo cáo gốc." if is_vietnamese else "Automatically condensed from conclusions already present in the native report.",
        "summary_sections": "Tổng quan theo các phần" if is_vietnamese else "Overview by report section",
        "scope": "Phạm vi" if is_vietnamese else "Coverage",
        "decision": "Kết luận" if is_vietnamese else "Conclusion",
        "key_point": "Điểm chính" if is_vietnamese else "Key point",
        "summary_overview": "Tóm tắt điều hành" if is_vietnamese else "Executive summary",
        "action": "Hành động cần theo dõi" if is_vietnamese else "Action to monitor",
        "disclaimer": "Không phải tư vấn đầu tư hoặc lệnh giao dịch." if is_vietnamese else "Not investment advice or an order instruction.",
    }
    font_name = _register_unicode_report_pdf_font() if is_vietnamese else _register_report_pdf_font(prefer_cjk=_has_cjk_text(content))
    buffer = BytesIO()
    page_width, _ = A4
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=16 * mm,
        leftMargin=16 * mm,
        topMargin=18 * mm,
        bottomMargin=18 * mm,
        title=labels["title"],
    )
    styles = getSampleStyleSheet()
    base = ParagraphStyle(
        "TradingAgentsPdfBase",
        parent=styles["Normal"],
        fontName=font_name,
        fontSize=10,
        leading=15.5,
        textColor=colors.HexColor("#273449"),
        spaceAfter=7,
    )
    title = ParagraphStyle(
        "TradingAgentsPdfTitle",
        parent=base,
        fontSize=21,
        leading=27,
        textColor=colors.white,
    )
    subtitle = ParagraphStyle(
        "TradingAgentsPdfSubtitle",
        parent=base,
        fontSize=8.5,
        leading=12,
        textColor=colors.HexColor("#cbd5e1"),
    )
    heading = ParagraphStyle(
        "TradingAgentsPdfHeading",
        parent=base,
        fontSize=13.5,
        leading=18,
        textColor=colors.HexColor("#12355b"),
        spaceBefore=10,
        spaceAfter=5,
    )
    subheading = ParagraphStyle(
        "TradingAgentsPdfSubheading",
        parent=heading,
        fontSize=11,
        leading=15,
        spaceBefore=8,
        spaceAfter=4,
    )
    document_heading = ParagraphStyle(
        "TradingAgentsPdfDocumentHeading",
        parent=heading,
        fontSize=16,
        leading=22,
        textColor=colors.HexColor("#102f55"),
        spaceBefore=12,
        spaceAfter=7,
    )
    small = ParagraphStyle(
        "TradingAgentsPdfSmall",
        parent=base,
        fontSize=8,
        leading=11,
        textColor=colors.HexColor("#64748b"),
    )
    bullet = ParagraphStyle(
        "TradingAgentsPdfBullet",
        parent=base,
        leftIndent=7 * mm,
        firstLineIndent=-4 * mm,
        bulletIndent=0,
        spaceAfter=3,
    )
    ordered = ParagraphStyle(
        "TradingAgentsPdfOrdered",
        parent=base,
        leftIndent=8 * mm,
        firstLineIndent=-5 * mm,
        spaceAfter=3,
    )
    table_header = ParagraphStyle(
        "TradingAgentsPdfTableHeader",
        parent=small,
        fontSize=8.2,
        leading=10.5,
        textColor=colors.HexColor("#17395f"),
    )
    table_cell = ParagraphStyle(
        "TradingAgentsPdfTableCell",
        parent=base,
        fontSize=8.7,
        leading=11.5,
        spaceAfter=0,
    )

    def escaped(value: object) -> str:
        return _plain_text(value).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").strip()

    def formatted(value: object) -> str:
        text = escaped(value)
        text = re.sub(r"`([^`]+)`", r'<font color="#0f5f7a">\1</font>', text)
        text = re.sub(r"\*\*(.+?)\*\*", r"<b>\1</b>", text)
        text = re.sub(r"(?<!\*)\*([^*]+)\*(?!\*)", r"<i>\1</i>", text)
        return text

    def paragraph(value: object, style: ParagraphStyle = base) -> Paragraph:
        return Paragraph(formatted(value).replace("\n", "<br/>"), style)

    lines = (content or "").replace("\r\n", "\n").replace("\r", "\n").split("\n")
    llm_summary = dict(executive_summary) if isinstance(executive_summary, Mapping) else {}
    story: list[object] = []

    def compact_summary(value: str, limit: int = 260) -> str:
        cleaned = re.sub(r"\s+", " ", re.sub(r"[*`#]", "", value)).strip()
        if len(cleaned) <= limit:
            return cleaned
        return f"{cleaned[:limit].rsplit(' ', 1)[0].rstrip()}..."

    def build_summary_rows() -> list[tuple[str, str]]:
        section_titles = [
            re.sub(r"^[IVXLC]+\.\s*", "", match.group(1)).strip()
            for raw_line in lines
            if (match := re.match(r"^##\s+(.+)$", raw_line.strip()))
        ]
        scope = ", ".join(section_titles[:3])
        if len(section_titles) > 3:
            scope = f"{scope} và {len(section_titles) - 3} phần khác"
        rows: list[tuple[str, str]] = [(labels["scope"], compact_summary(scope or labels["summary_note"], 180))]
        if llm_summary:
            overview = compact_summary(str(llm_summary.get("overview") or ""), 820)
            conclusion = compact_summary(str(llm_summary.get("conclusion") or ""), 260)
            key_points = "\n".join(compact_summary(str(item), 160) for item in (llm_summary.get("key_points") or [])[:3])
            if conclusion:
                rows.append((labels["decision"], conclusion))
            if overview:
                rows.append((labels["summary_overview"], overview))
            if key_points:
                rows.append((labels["action"], key_points))
            return rows[:4]
        field_patterns = (
            (labels["decision"], ("khuyến nghị", "recommendation", "rating", "đánh giá", "quyết định")),
            (labels["key_point"], ("tóm tắt điều hành", "executive summary", "rationale", "luận điểm")),
            (labels["action"], ("hành động chiến lược", "strategic actions", "action", "hành động")),
        )
        seen_labels: set[str] = set()
        for raw_line in lines:
            match = re.match(r"^\s*(?:[-*+]\s+)?(?:\*\*)?(.+?)(?:\*\*)?\s*:\s*(.+)$", raw_line.strip())
            if not match:
                continue
            field_name = match.group(1).strip().casefold()
            field_value = compact_summary(match.group(2))
            if not field_value:
                continue
            for output_label, candidates in field_patterns:
                if output_label not in seen_labels and any(candidate in field_name for candidate in candidates):
                    rows.append((output_label, field_value))
                    seen_labels.add(output_label)
                    break
        return rows[:4]

    def build_section_summaries() -> list[tuple[str, str]]:
        if llm_summary:
            return [
                (compact_summary(str(item.get("title") or ""), 180), compact_summary(str(item.get("summary") or ""), 420))
                for item in (llm_summary.get("sections") or [])[:5]
                if isinstance(item, Mapping) and item.get("title") and item.get("summary")
            ]
        summaries: list[tuple[str, str]] = []
        section_index = 0
        while section_index < len(lines):
            match = re.match(r"^##\s+(.+)$", lines[section_index].strip())
            if not match:
                section_index += 1
                continue
            section_title = re.sub(r"^[IVXLC]+\.\s*", "", match.group(1)).strip()
            section_index += 1
            excerpts: list[str] = []
            active_subheading = ""
            while section_index < len(lines) and not re.match(r"^##\s+", lines[section_index].strip()):
                line = lines[section_index].strip()
                subheading = re.match(r"^###\s+(.+)$", line)
                if subheading:
                    active_subheading = subheading.group(1).strip()
                elif line and not line.startswith("|") and not re.match(r"^Generated\s*:", line, flags=re.IGNORECASE):
                    text = re.sub(r"^[-*+]\s+", "", line)
                    if active_subheading:
                        text = f"{active_subheading}: {text}"
                        active_subheading = ""
                    excerpts.append(text)
                section_index += 1
            detail = compact_summary(" ".join(excerpts), 175)
            if detail:
                summaries.append((section_title, detail))
        return summaries[:5]

    def append_report_summary() -> None:
        summary_title = ParagraphStyle(
            "TradingAgentsPdfSummaryTitle", parent=heading, fontSize=13, leading=17, textColor=colors.HexColor("#12355b"), spaceAfter=2
        )
        summary_rows = build_summary_rows()
        entries = [
            [Paragraph(labels["summary"], summary_title), Paragraph(labels["summary_note"], small)],
        ]
        for row_label, row_value in summary_rows:
            entries.append([Paragraph(row_label, small), paragraph(row_value)])
        summary = Table(entries, colWidths=[doc.width * 0.25, doc.width * 0.75], hAlign="LEFT")
        summary.setStyle(TableStyle([
            ("SPAN", (0, 0), (1, 0)),
            ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#f2f8f4")),
            ("LINEBEFORE", (0, 0), (0, -1), 3, colors.HexColor("#39a36a")),
            ("GRID", (0, 1), (-1, -1), 0.35, colors.HexColor("#dbece1")),
            ("LEFTPADDING", (0, 0), (-1, -1), 10),
            ("RIGHTPADDING", (0, 0), (-1, -1), 10),
            ("TOPPADDING", (0, 0), (-1, -1), 7),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 7),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ]))
        story.extend([Spacer(1, 5 * mm), summary, Spacer(1, 3 * mm)])

        section_rows = [[Paragraph(labels["summary_sections"], subheading)]]
        for section_title, excerpt in build_section_summaries():
            section_rows.append([Paragraph(f"<b>{formatted(section_title)}</b><br/>{formatted(excerpt)}", base)])
        if len(section_rows) > 1:
            section_summary = Table(section_rows, colWidths=[doc.width], hAlign="LEFT")
            section_summary.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#f7fafc")),
                ("BACKGROUND", (0, 1), (-1, -1), colors.white),
                ("LINEABOVE", (0, 0), (-1, 0), 0.65, colors.HexColor("#cfdee9")),
                ("LINEBELOW", (0, 0), (-1, -1), 0.35, colors.HexColor("#e1eaf1")),
                ("LEFTPADDING", (0, 0), (-1, -1), 10),
                ("RIGHTPADDING", (0, 0), (-1, -1), 10),
                ("TOPPADDING", (0, 0), (-1, -1), 5),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ]))
            story.extend([section_summary, Spacer(1, 2 * mm)])
        story.append(PageBreak())

    header = Table(
        [[
            [Paragraph(labels["title"], title), Paragraph(labels["subtitle"], subtitle)],
            Paragraph(f"{escaped(market)}<br/><b>{escaped(symbol)}</b>", ParagraphStyle(
                "TradingAgentsPdfTarget", parent=base, fontSize=12, leading=17, textColor=colors.white, alignment=TA_RIGHT
            )),
        ]],
        colWidths=[doc.width * 0.72, doc.width * 0.28],
    )
    header.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#102033")),
        ("LEFTPADDING", (0, 0), (-1, -1), 14),
        ("RIGHTPADDING", (0, 0), (-1, -1), 14),
        ("TOPPADDING", (0, 0), (-1, -1), 14),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 14),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
    ]))
    story.extend([header, Spacer(1, 6 * mm)])

    metadata = Table([[
        [Paragraph(labels["asset"], small), paragraph(f"{market}: {symbol}")],
        [Paragraph(labels["date"], small), paragraph(analysis_date)],
        [Paragraph(labels["run"], small), paragraph(run_id)],
    ]], colWidths=[doc.width / 3] * 3, hAlign="LEFT")
    metadata.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#f5f8fc")),
        ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#d8e1ee")),
        ("INNERGRID", (0, 0), (-1, -1), 5, colors.white),
        ("LEFTPADDING", (0, 0), (-1, -1), 9),
        ("RIGHTPADDING", (0, 0), (-1, -1), 9),
        ("TOPPADDING", (0, 0), (-1, -1), 7),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 7),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
    ]))
    story.append(metadata)
    append_report_summary()

    paragraph_lines: list[str] = []

    def flush_paragraph() -> None:
        if paragraph_lines:
            story.append(paragraph(" ".join(paragraph_lines)))
            paragraph_lines.clear()

    def append_section(title_text: str) -> None:
        heading_row = Table([[paragraph(title_text, heading)]], colWidths=[doc.width], hAlign="LEFT")
        heading_row.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#edf5fa")),
            ("LINEBEFORE", (0, 0), (0, -1), 3, colors.HexColor("#27a3c4")),
            ("LEFTPADDING", (0, 0), (-1, -1), 7),
            ("RIGHTPADDING", (0, 0), (-1, -1), 8),
            ("TOPPADDING", (0, 0), (-1, -1), 5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ]))
        story.extend([Spacer(1, 3 * mm), heading_row, Spacer(1, 1.5 * mm)])

    def split_table_row(value: str) -> list[str]:
        return [cell.strip() for cell in value.strip().strip("|").split("|")]

    def is_table_divider(cells: list[str]) -> bool:
        return bool(cells) and all(re.fullmatch(r":?-{3,}:?", cell.strip()) for cell in cells)

    def append_table(rows: list[list[str]]) -> None:
        if not rows:
            return
        has_header = len(rows) > 1 and is_table_divider(rows[1])
        body_rows = [rows[0]] + rows[2:] if has_header else rows
        column_count = max(len(row) for row in body_rows)
        padded_rows = [row + [""] * (column_count - len(row)) for row in body_rows]
        rendered_rows = []
        for row_index, row in enumerate(padded_rows):
            style = table_header if has_header and row_index == 0 else table_cell
            rendered_rows.append([paragraph(cell, style) for cell in row])
        report_table = Table(
            rendered_rows,
            colWidths=[doc.width / column_count] * column_count,
            repeatRows=1 if has_header else 0,
            hAlign="LEFT",
        )
        report_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#e8f1f8") if has_header else colors.white),
            ("BACKGROUND", (0, 1 if has_header else 0), (-1, -1), colors.HexColor("#fbfdff")),
            ("GRID", (0, 0), (-1, -1), 0.45, colors.HexColor("#d6e2ed")),
            ("LEFTPADDING", (0, 0), (-1, -1), 7),
            ("RIGHTPADDING", (0, 0), (-1, -1), 7),
            ("TOPPADDING", (0, 0), (-1, -1), 6),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ]))
        story.extend([Spacer(1, 2 * mm), report_table, Spacer(1, 2 * mm)])

    line_index = 0
    while line_index < len(lines):
        raw_line = lines[line_index]
        line = raw_line.strip()
        if not line:
            flush_paragraph()
            line_index += 1
            continue
        match = re.match(r"^(#{1,3})\s+(.+)$", line)
        if match:
            flush_paragraph()
            level = len(match.group(1))
            heading_text = match.group(2)
            if level == 1:
                story.extend([Spacer(1, 4 * mm), paragraph(heading_text, document_heading), HRFlowable(width="100%", thickness=0.7, color=colors.HexColor("#b8cad9")), Spacer(1, 1.5 * mm)])
            elif level == 2:
                append_section(heading_text)
            else:
                story.append(paragraph(heading_text, subheading))
            line_index += 1
            continue
        if line.startswith("|") and line.endswith("|"):
            flush_paragraph()
            raw_rows: list[list[str]] = []
            while line_index < len(lines):
                candidate = lines[line_index].strip()
                if not (candidate.startswith("|") and candidate.endswith("|")):
                    break
                raw_rows.append(split_table_row(candidate))
                line_index += 1
            append_table(raw_rows)
            continue
        bullet_match = re.match(r"^(\s*)[-*+]\s+(.+)$", raw_line)
        if bullet_match:
            flush_paragraph()
            indent = min(len(bullet_match.group(1).expandtabs(2)), 8)
            item_style = ParagraphStyle(f"TradingAgentsPdfBullet{line_index}", parent=bullet, leftIndent=7 * mm + indent * 1.3)
            story.append(paragraph(f"• {bullet_match.group(2)}", item_style))
            line_index += 1
            continue
        ordered_match = re.match(r"^\s*(\d+[.)])\s+(.+)$", raw_line)
        if ordered_match:
            flush_paragraph()
            story.append(paragraph(f"{ordered_match.group(1)} {ordered_match.group(2)}", ordered))
            line_index += 1
            continue
        paragraph_lines.append(line)
        line_index += 1
    flush_paragraph()

    def draw_page(canvas_obj: object, document: object) -> None:
        canvas_obj.saveState()
        canvas_obj.setFillColor(colors.HexColor("#64748b"))
        canvas_obj.setFont(font_name, 7.5)
        canvas_obj.drawString(doc.leftMargin, 9 * mm, labels["disclaimer"])
        canvas_obj.drawRightString(page_width - doc.rightMargin, 9 * mm, f"DataVest - TradingAgents - {document.page}")
        canvas_obj.restoreState()

    doc.build(story, onFirstPage=draw_page, onLaterPages=draw_page)
    return buffer.getvalue()

